#Frank Carter
#10/11/2019
#All three assignments are in this one file, you can call each function with the following inputs: star() circles() landscape()
import turtle
import random

bob = turtle.Turtle()
#draws and colors a star
def star():
    bob.fillcolor("blue")
    bob.begin_fill()
    for x in range(0,5):
        bob.forward(100)
        bob.left(72)
        bob.forward(100)
        bob.right(144)
    bob.end_fill()
#draws 5 circles of different colors
#the circle function draws a circle with a specified radius and color
def circle(radius,color):
    bob.fillcolor(color)
    bob.begin_fill()
    bob.circle(radius)
    bob.end_fill()
    #the circles function draws the actual circles
def circles():
    #moves the turtle to the left side of the interface
    bob.penup()
    bob.right(180)
    bob.forward(200)
    bob.right(180)
    bob.pendown()
#Circle 1
    circle(50,"blue")
#Circle2
    bob.penup()
    bob.right(90)
    bob.forward(100)
    bob.left(90)
    bob.forward(100)
    bob.pendown()
    circle(50,"yellow")
#Circle 3
    bob.penup()
    bob.left(90)
    bob.forward(100)
    bob.right(90)
    bob.forward(100)
    bob.pendown()
    circle(50,"black")
#Circle 4
    bob.penup()
    bob.right(90)
    bob.forward(100)
    bob.left(90)
    bob.forward(100)
    bob.pendown()
    circle(50,"green")
#Circle 5
    bob.penup()
    bob.left(90)
    bob.forward(100)
    bob.right(90)
    bob.forward(100)
    bob.pendown()
    circle(50,"red")

#Draws clouds for the landscape function
def clouds(radius):
    bob.fillcolor("white")
    bob.begin_fill()
    bob.circle(radius)
    bob.end_fill()
    bob.penup()

def landscape():
    bob.penup()
    bob.right(180)
    bob.forward(500)
    bob.left(90)
    bob.forward(500)
    bob.left(90)
    bob.pendown()
    bob.fillcolor("blue")
    bob.begin_fill()
    #Makes the sky
    for x in range(0,4):
        bob.forward(1000)
        bob.left(90)
    bob.end_fill()
    #Makes the grass
    bob.left(90)
    bob.forward(200)
    bob.right(90)
    bob.fillcolor("green")
    bob.begin_fill()
    bob.forward(1000)
    bob.right(90)
    bob.forward(200)
    bob.right(90)
    bob.forward(1000)
    bob.right(90)
    bob.forward(200)
    bob.end_fill()
    bob.penup()
    bob.right(90)
    bob.forward(350)
    #Builds a house
    bob.left(90)
    bob.pendown()
    bob.fillcolor("yellow")
    bob.begin_fill()
    for x in range(0,2):
        bob.forward(150)
        bob.right(90)
        bob.forward(250)
        bob.right(90)
    bob.end_fill()
    bob.forward(150)
    #Builds a roof
    bob.fillcolor("red")
    bob.begin_fill()
    bob.right(45)
    bob.forward(176.8)
    bob.right(90)
    bob.forward(176.8)
    bob.end_fill()
    #Builds a door
    bob.penup()
    bob.right(45)
    bob.forward(150)
    bob.right(90)
    bob.pendown()
    bob.fillcolor("black")
    bob.begin_fill()
    bob.forward(110)
    bob.right(90)
    bob.forward(50)
    bob.left(90)
    bob.forward(30)
    bob.left(90)
    bob.forward(50)
    bob.left(90)
    bob.forward(30)
    bob.end_fill()
    #Draw clouds
    bob.penup()
    bob.goto(-220, 150)
    clouds(50)
    bob.left(90)
    bob.forward(30)
    bob.right(90)
    bob.forward(50)
    clouds(50)
    bob.right(90)
    bob.forward(50)
    bob.left(90)
    bob.forward(40)
    clouds(50)
    #Cloud #2
    bob.penup()
    bob.goto(220, 100)
    clouds(50)
    bob.left(90)
    bob.forward(60)
    bob.right(90)
    bob.forward(40)
    clouds(50)
    bob.right(90)
    bob.forward(50)
    bob.left(90)
    bob.forward(20)
    clouds(50)
    #Cloud #3
    bob.penup()
    bob.goto(40,40)
    clouds(50)
    bob.left(90)
    bob.forward(40)
    bob.right(90)
    bob.forward(60)
    clouds(50)
    bob.right(90)
    bob.forward(50)
    bob.left(90)
    bob.forward(10)
    clouds(50)
    #Corner Sun :)
    bob.goto(-350,260)
    bob.fillcolor("yellow")
    bob.begin_fill()
    bob.circle(100)
    bob.end_fill()
    #Tree
    bob.goto(170,-300)
    bob.forward(50)
    bob.pendown()
    bob.fillcolor("brown")
    bob.begin_fill()
    bob.left(90)
    bob.forward(200)
    bob.right(90)
    bob.forward(30)
    bob.right(90)
    bob.forward(200)
    bob.right(90)
    bob.forward(30)
    bob.end_fill()
    bob.right(90)
    bob.forward(170)
    bob.right(90)
    bob.forward(10)
    bob.fillcolor("green")
    bob.begin_fill()
    bob.circle(50)
    bob.end_fill()
    bob.penup()
    bob.left(90)
    bob.forward(20)
    bob.pendown()
    bob.fillcolor("green")
    bob.begin_fill()
    bob.circle(50)
    bob.end_fill()
    bob.penup()
    bob.right(90)
    bob.forward(10)
    bob.right(90)
    bob.forward(20)
    bob.pendown()
    bob.fillcolor("green")
    bob.begin_fill()
    bob.circle(50)
    bob.end_fill()
    #Window
    bob.penup()
    bob.goto(-80,-200)
    bob.pendown()
    bob.fillcolor("blue")
    bob.begin_fill()
    for x in range(0,4):
        bob.forward(40)
        bob.right(90)
    bob.end_fill()
    

